# This file describes a blueprint for use in Crafter Studio

# The version of this type of this file
descriptorVersion: 1

# Describe the blueprint
blueprint:
  id: org.craftercms.blueprint.headless_blog
  name: Headless Blog Blueprint
  tags: blueprint,website,headless,blog
  version:
    major: 1
    minor: 0
    patch: 0
  description: |
    Headless blog blueprint
  website:
    name: Headless Blog Blueprint
    url: https://craftercms.org
  media:
    screenshots:
      - screenshot:
          title: Author
          description: Screenshot of the author item
          url: /studio/static-assets/images/blueprints/headless_blog/bp_blog_author.png
      - screenshot:
          title: Post
          description: Screenshot of the post item
          url: /studio/static-assets/images/blueprints/headless_blog/bp_blog_post.png
    developer:
      company:
        name: Crafter Software
        email: info@craftersoftware.com
        url: https://craftersoftware.com/
  build:
    id: c3d2a5444e6a24b5e0481d6ba87901d0b02716c8
    date: 2019-01-23T00:00:00Z
  license:
      name: MIT
      url: https://opensource.org/licenses/MIT
  craftercmsVersionsSupported:
    - version: 3.1.0
  searchEngine: Elasticsearch
